version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=tasks'
    ports:
      - '5431:5431'
    command: -p 5431


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
